#import <Foundation/Foundation.h>
#import "SWGLoadingCustomBean.h"
#import "SWGMessageResult.h"
#import "SWGOrderAbroadPackBean.h"
#import "SWGOrderPack.h"
#import "SWGScreenGoods.h"
#import "SWGApi.h"
#import "SWGConfirmLoadingBean.h"
#import "SWGComeStockBean.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGOrderPackControllerApi: NSObject <SWGApi>

extern NSString* kSWGOrderPackControllerApiErrorDomain;
extern NSInteger kSWGOrderPackControllerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 删除装货信息
/// 删除装货信息
///
/// @param authorization 令牌 (default to 去其他请求中获取heard中token参数)
/// @param orderPackIdList 装货单id
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMessageResult*
-(NSURLSessionTask*) cancelPackagesUsingGETWithAuthorization: (NSString*) authorization
    orderPackIdList: (NSArray<NSNumber *>*) orderPackIdList
    completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;


//放货
-(NSURLSessionTask*) comeStockUsingPOSTWithAuthorization: (NSString*) authorization
                                                    bean: (NSArray<SWGComeStockBean>*) bean
                                       completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;

/// 比较包号是否已装货
/// 比较包号是否已装货
///
/// @param authorization 令牌 (default to 去其他请求中获取heard中token参数)
/// @param orderId 订单id
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMessageResult*
-(NSURLSessionTask*) comparePackagesUsingGETWithAuthorization: (NSString*) authorization
    orderId: (NSNumber*) orderId
    completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;

-(NSURLSessionTask*) confirmLoadingUsingPOSTWithAuthorization: (NSString*) authorization
                                                        beans: (NSArray<SWGConfirmLoadingBean>*) beans
                                            completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;

/// 确认提货
/// 确认提货
///
/// @param authorization 令牌 (default to 去其他请求中获取heard中token参数)
/// @param orderId 订单id
/// @param buyerId 买家id
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMessageResult*
-(NSURLSessionTask*) confirmLoadingUsingGETWithAuthorization: (NSString*) authorization
    orderId: (NSNumber*) orderId
    buyerId: (NSNumber*) buyerId
    completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;


/// 装货信息自定义添加
/// 装货信息自定义添加
///
/// @param authorization 令牌 (default to 去其他请求中获取heard中token参数)
/// @param loadingCustomBean loadingCustomBean (optional)
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMessageResult*
-(NSURLSessionTask*) insertLoadingCustomUsingPOSTWithAuthorization: (NSString*) authorization
    loadingCustomBean: (SWGLoadingCustomBean*) loadingCustomBean
    completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;


/// 手动添加装货单
/// 手动添加装货单
///
/// @param authorization 令牌 (default to 去其他请求中获取heard中token参数)
/// @param bean bean (optional)
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMessageResult*
-(NSURLSessionTask*) insertOrderPackUsingPOSTWithAuthorization: (NSString*) authorization
    bean: (SWGOrderPack*) bean
    completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;


/// 订单外添加装货单
/// 订单外添加装货单
///
/// @param authorization 令牌 (default to 去其他请求中获取heard中token参数)
/// @param bean bean (optional)
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMessageResult*
-(NSURLSessionTask*) orderAbroadPackUsingPOSTWithAuthorization: (NSString*) authorization
    bean: (NSArray<SWGOrderAbroadPackBean>*) bean
    completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;


/// 根据订单id显示装货信息
/// 根据订单id显示商品装货信息
///
/// @param authorization 令牌 (default to 去其他请求中获取heard中token参数)
/// @param orderId 订单id
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMessageResult*
-(NSURLSessionTask*) selectOrderPackUsingGETWithAuthorization: (NSString*) authorization
    orderId: (NSNumber*) orderId
    completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;


/// 装货单显示所有商品的库存
/// 装货单显示所有商品的库存
///
/// @param authorization 令牌 (default to 去其他请求中获取heard中token参数)
/// @param screenGoods screenGoods (optional)
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMessageResult*
-(NSURLSessionTask*) selectStockUsingPOST1WithAuthorization: (NSString*) authorization
    screenGoods: (SWGScreenGoods*) screenGoods
    completionHandler: (void (^)(SWGMessageResult* output, NSError* error)) handler;



@end
