#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGAddMerchandiseBean
@end

@interface SWGAddMerchandiseBean : SWGObject


@property(nonatomic) NSNumber* cubicNum;

@property(nonatomic) NSString* delivery;

@property(nonatomic) NSString* goodsUnit;

@property(nonatomic) NSNumber* length;

@property(nonatomic) NSNumber* lengthAttrId;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSNumber* piecesNum;

@property(nonatomic) NSNumber* piecesNumAttrId;

@property(nonatomic) NSNumber* price;

@property(nonatomic) NSNumber* warehouseId;

@property(nonatomic) NSString* warehouseName;

@end
