#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGBoardPriceUpdate
@end

@interface SWGBoardPriceUpdate : SWGObject


@property(nonatomic) NSString* brand;

@property(nonatomic) NSString* category;

@property(nonatomic) NSString* company;

@property(nonatomic) NSString* cubicNum;

@property(nonatomic) NSString* department;

@property(nonatomic) NSString* grade;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* length;

@property(nonatomic) NSString* moisture;

@property(nonatomic) NSString* number;

@property(nonatomic) NSString* origin;

@property(nonatomic) NSString* pieceNum;

@property(nonatomic) NSString* price;

@property(nonatomic) NSString* species;

@property(nonatomic) NSString* thickness;

@property(nonatomic) NSString* warehouse;

@property(nonatomic) NSString* width;

@end
