#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGBrandTable
@end

@interface SWGBrandTable : SWGObject


@property(nonatomic) NSNumber* categoryId;

@property(nonatomic) NSDate* createTime;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* enName;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* keywords;

@property(nonatomic) NSString* logo;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* status;

@property(nonatomic) NSDate* updateTime;

@property(nonatomic) NSString* webUrl;

@end
