#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGConfirmLoadingBean
@end

@interface SWGConfirmLoadingBean : SWGObject


@property(nonatomic) NSNumber* buyNumber;

@property(nonatomic) NSString* buyPrice;

@property(nonatomic) NSNumber* cubicNum;

@property(nonatomic) NSNumber* orderId;

@property(nonatomic) NSNumber* orderStatus;

@property(nonatomic) NSNumber* userId;

@end
