#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCategoryLogBean
@end

@interface SWGCategoryLogBean : SWGObject


@property(nonatomic) NSString* address;

@property(nonatomic) NSString* brand;

@property(nonatomic) NSString* caliber;

@property(nonatomic) NSNumber* categoryId;

@property(nonatomic) NSString* company;

@property(nonatomic) NSString* cubicNum;

@property(nonatomic) NSString* department;

@property(nonatomic) NSString* grade;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* length;

@property(nonatomic) NSString* moisture;

@property(nonatomic) NSString* origin;

@property(nonatomic) NSString* price;

@property(nonatomic) NSString* remarks;

@property(nonatomic) NSString* rootNum;

@property(nonatomic) NSString* species;

@property(nonatomic) NSString* warehouse;

@end
