#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGoodsWarehouseBean
@end

@interface SWGGoodsWarehouseBean : SWGObject

/* 商品id [optional]
 */
@property(nonatomic) NSNumber* goodsId;

@property(nonatomic) NSNumber* _id;
/* 锁定数量 [optional]
 */
@property(nonatomic) NSNumber* lockNum;
/* 包号 [optional]
 */
@property(nonatomic) NSString* packages;
/* 售价 [optional]
 */
@property(nonatomic) NSNumber* salePrice;
/* 商品库存量 [optional]
 */
@property(nonatomic) NSNumber* stockNum;
/* 店铺id [optional]
 */
@property(nonatomic) NSNumber* storeId;
/* 仓库id [optional]
 */
@property(nonatomic) NSNumber* warehouseId;

@end
