#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInvoiceTableBean
@end

@interface SWGInvoiceTableBean : SWGObject

/* 买家备注 [optional]
 */
@property(nonatomic) NSString* buyerMemo;
/* 创建时间 [optional]
 */
@property(nonatomic) NSDate* createTime;
/* 开票方ID [optional]
 */
@property(nonatomic) NSNumber* fromId;
/* ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* 开票地址 [optional]
 */
@property(nonatomic) NSString* invoiceAddress;
/* 开票内容 [optional]
 */
@property(nonatomic) NSString* invoiceContent;
/* 发票金额 [optional]
 */
@property(nonatomic) NSNumber* invoiceMoney;
/* 发票号码 [optional]
 */
@property(nonatomic) NSString* invoiceNumber;
/* 运费 [optional]
 */
@property(nonatomic) NSNumber* invoicePrice;
/* 订单SN [optional]
 */
@property(nonatomic) NSString* invoiceSn;
/* 发票类型(1,普通增值税;2,专用增值税) [optional]
 */
@property(nonatomic) NSNumber* invoiceTax;
/* 开票税号 [optional]
 */
@property(nonatomic) NSString* invoiceTaxNo;
/* 开票电话 [optional]
 */
@property(nonatomic) NSString* invoiceTelephone;
/* 发票抬头 [optional]
 */
@property(nonatomic) NSString* invoiceTitle;
/* 发票类型(0,无需发票;1,个人发票;2,公司发票) [optional]
 */
@property(nonatomic) NSNumber* invoiceType;
/* 邮寄地址 [optional]
 */
@property(nonatomic) NSString* mailingAddress;
/* 物流名称 [optional]
 */
@property(nonatomic) NSString* postName;
/* 物流单号 [optional]
 */
@property(nonatomic) NSString* postNo;
/* 物流时间 [optional]
 */
@property(nonatomic) NSDate* postTime;
/* 参考URI [optional]
 */
@property(nonatomic) NSString* reffer;
/* 卖家备注 [optional]
 */
@property(nonatomic) NSString* sellerMemo;
/* 状态(0,删除;1,正常;) [optional]
 */
@property(nonatomic) NSNumber* status;
/* 接受方ID [optional]
 */
@property(nonatomic) NSNumber* toId;
/* 更新时间 [optional]
 */
@property(nonatomic) NSDate* updateTime;

@end
