#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGLoadingCustomBean
@end

@interface SWGLoadingCustomBean : SWGObject


@property(nonatomic) NSString* brandName;

@property(nonatomic) NSNumber* cubicNum;

@property(nonatomic) NSString* department;

@property(nonatomic) NSString* grade;

@property(nonatomic) NSString* length;

@property(nonatomic) NSNumber* orderId;

@property(nonatomic) NSString* packetNum;

@property(nonatomic) NSString* piecesNum;

@property(nonatomic) NSString* price;

@property(nonatomic) NSString* species;

@property(nonatomic) NSString* thickness;

@property(nonatomic) NSString* warehouse;

@property(nonatomic) NSString* width;

@property(nonatomic) NSString* packages;

@property(nonatomic)NSNumber* categoryId;

@end
