#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLogisticsPriceBean.h"
@protocol SWGLogisticsPriceBean;
@class SWGLogisticsPriceBean;



@protocol SWGMallLogisticsBean
@end

@interface SWGMallLogisticsBean : SWGObject


@property(nonatomic) NSDate* createTime;
/* 装卸次数 [optional]
 */
@property(nonatomic) NSString* frequency;

@property(nonatomic) NSNumber* _id;
/* 车长 [optional]
 */
@property(nonatomic) NSNumber* length;
/* 装货地 [optional]
 */
@property(nonatomic) NSString* loading;
/* 装货详细地址 [optional]
 */
@property(nonatomic) NSString* loadingAddress;

@property(nonatomic) NSArray<SWGLogisticsPriceBean>* logisticsPriceList;
/* 备注 [optional]
 */
@property(nonatomic) NSString* memo;
/* 联系电话 [optional]
 */
@property(nonatomic) NSNumber* phone;
/* 状态（0、取消1、下单2、加单、3报价、4、确认5、信息6、完成） [optional]
 */
@property(nonatomic) NSNumber* status;
/* 装货时间 [optional]
 */
@property(nonatomic) NSDate* time;
/* 货物种类 [optional]
 */
@property(nonatomic) NSNumber* type;
/* 卸货地 [optional]
 */
@property(nonatomic) NSString* unload;
/* 卸货详细地址 [optional]
 */
@property(nonatomic) NSString* unloadAddress;

@property(nonatomic) NSDate* updateTime;
/* 用户id [optional]
 */
@property(nonatomic) NSNumber* userId;
/* 联系人 [optional]
 */
@property(nonatomic) NSString* userName;
/* 重量 [optional]
 */
@property(nonatomic) NSNumber* weight;

@end
