#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGMallCategoryAttribute.h"
@protocol SWGMallCategoryAttribute;
@class SWGMallCategoryAttribute;



@protocol SWGMallCategoryTable
@end

@interface SWGMallCategoryTable : SWGObject


@property(nonatomic) NSString* categoryName;

@property(nonatomic) NSDate* createTime;

@property(nonatomic) NSNumber* display;

@property(nonatomic) NSString* expression;

@property(nonatomic) NSString* icon;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* level;

@property(nonatomic) SWGMallCategoryAttribute* mallCategoryAttribute;

@property(nonatomic) NSNumber* parentId;

@property(nonatomic) NSNumber* recommend;

@property(nonatomic) NSString* seoDescription;

@property(nonatomic) NSString* seoKeywords;

@property(nonatomic) NSNumber* sort;

@property(nonatomic) NSNumber* status;

@property(nonatomic) NSDate* updateTime;

@end
