#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGMallCategoryAttribute
@end

@interface SWGMallCategoryAttribute : SWGObject


@property(nonatomic) NSString* attrName;

@property(nonatomic) NSNumber* categoryId;

@property(nonatomic) NSNumber* condition;

@property(nonatomic) NSDate* createTime;

@property(nonatomic) NSString* defaultValue;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* inputData;

@property(nonatomic) NSNumber* isSpecification;

@property(nonatomic) NSNumber* required;

@property(nonatomic) NSNumber* sort;

@property(nonatomic) NSNumber* status;

@property(nonatomic) NSDate* updateTime;

@end
