#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGProductTable.h"
#import "SWGStoreGoodsAttributeBean.h"
#import "SWGWarestoreTable.h"
@protocol SWGProductTable;
@class SWGProductTable;
@protocol SWGStoreGoodsAttributeBean;
@class SWGStoreGoodsAttributeBean;
@protocol SWGWarestoreTable;
@class SWGWarestoreTable;



@protocol SWGOrderPackBean
@end

@interface SWGOrderPackBean : SWGObject

/* 商品数量 [optional]
 */
@property(nonatomic) NSNumber* buyNumber;

@property(nonatomic) NSNumber* number;

/* 商品价格 [optional]
 */
@property(nonatomic) NSString* buyPrice;

@property(nonatomic) NSNumber* cubicNumber;

@property(nonatomic) NSNumber* categoryId;

@property(nonatomic) NSNumber* stockNum;

@property(nonatomic) NSNumber* lockNum;

/* 创建时间 [optional]
 */
@property(nonatomic) NSDate* createTime;
/* 商品ID [optional]
 */
@property(nonatomic) NSNumber* goodsId;
/* 商品名称 [optional]
 */
@property(nonatomic) NSString* goodsName;
/* 订单详情ID [optional]
 */
@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSArray<SWGStoreGoodsAttributeBean>* lengthList;

@property(nonatomic) NSArray<SWGStoreGoodsAttributeBean>* numberList;
/* 订单ID [optional]
 */
@property(nonatomic) NSNumber* orderId;
/* 包号-逗号隔开 [optional]
 */
@property(nonatomic) NSString* packages;

@property(nonatomic) NSNumber* productId;

@property(nonatomic) NSArray<SWGProductTable>* productTableList;
/* 状态(1,正常；0,已取消) [optional]
 */
@property(nonatomic) NSNumber* status;
/* 更新时间 [optional]
 */
@property(nonatomic) NSDate* updateTime;

@property(nonatomic) NSNumber* warehouseId;

@property(nonatomic) NSArray<SWGWarestoreTable>* warestoreTableList;

@end
