#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGOrderDetailBean
@end

@interface SWGOrderDetailBean : SWGObject


@property(nonatomic) NSNumber* buyNumber;

@property(nonatomic) NSNumber* buyPrice;

@property(nonatomic) NSDate* createTime;

@property(nonatomic) NSNumber* goodsId;

@property(nonatomic) NSString* goodsName;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* orderId;

@property(nonatomic) NSString* packages;

@property(nonatomic) NSNumber* status;

@property(nonatomic) NSDate* updateTime;

@property(nonatomic) NSNumber* cubicNumber;

@end
