#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAddMerchandiseBean.h"
#import "SWGAttributeBean.h"
#import "SWGCommodityWarehouseBean.h"
@protocol SWGAddMerchandiseBean;
@class SWGAddMerchandiseBean;
@protocol SWGAttributeBean;
@class SWGAttributeBean;
@protocol SWGCommodityWarehouseBean;
@class SWGCommodityWarehouseBean;



@protocol SWGProductGoodsStoreBean
@end

@interface SWGProductGoodsStoreBean : SWGObject


@property(nonatomic) NSArray<SWGAddMerchandiseBean>* addMerchandiseBean;

@property(nonatomic) NSArray<SWGAttributeBean>* attributeBeans;

@property(nonatomic) NSNumber* brandId;

@property(nonatomic) NSString* brandName;

@property(nonatomic) NSNumber* categoryId;

@property(nonatomic) NSArray<SWGCommodityWarehouseBean>* commodityWarehouseBeans;

@property(nonatomic) NSString* describe;

@property(nonatomic) NSString* goodsImg;

@property(nonatomic) NSNumber* productId;

@property(nonatomic) NSNumber* storeId;

@property(nonatomic) NSString* title;

@property(nonatomic) NSNumber* type;

@property(nonatomic) NSString* video;

@end
