#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAttributeBean.h"
@protocol SWGAttributeBean;
@class SWGAttributeBean;



@protocol SWGScreenGoods
@end

@interface SWGScreenGoods : SWGObject


@property(nonatomic) NSArray<SWGAttributeBean>* attributeList;

@property(nonatomic) NSNumber* brandId;

@property(nonatomic) NSNumber* categoryId;

@property(nonatomic) NSNumber* cubicNumId;

@property(nonatomic) NSString* length;

@property(nonatomic) NSNumber* pageNum;

@property(nonatomic) NSNumber* pageSize;

@property(nonatomic) NSString* piecesNum;

@property(nonatomic) NSString* productName;

@property(nonatomic) NSNumber* storeId;

@property(nonatomic) NSNumber* warehouseId;

@end
