#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Youmu Cloud Framework Swagger API 
* https://www.51wood.com
*
* OpenAPI spec version: 1.0
* Contact: archerchu@163.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGWarestoreTable
@end

@interface SWGWarestoreTable : SWGObject


@property(nonatomic) NSString* address;

@property(nonatomic) NSNumber* areaId;

@property(nonatomic) NSString* areaName;

@property(nonatomic) NSDate* createTime;

@property(nonatomic) NSNumber* creatorId;

@property(nonatomic) NSNumber* deptId;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* location;

@property(nonatomic) NSString* memo;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* phone;

@property(nonatomic) NSString* savePrice;

@property(nonatomic) NSNumber* status;

@property(nonatomic) NSNumber* tenantId;

@property(nonatomic) NSDate* updateTime;

@end
